[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
problem1_9 = { path = "../problem1_9"}
problem10_19 = { path = "../problem10_19"}
problem20_29 = { path = "../problem20_29"}
